### ISSUE TITLE
Review: `cosmology.py`

### ISSUE THREAD

**Issue by zodoctor** [FarrOutLab/GWInferno#24]
Create unit test to ensure this matches outputs from astropy

**Comment by Qazalbash** [comment]
There is a mistake in an argument; there is no `max_DL` in `Cosmology.extend`.

https://github.com/FarrOutLab/GWInferno/blob/9be48191a2bc236959d66c59669c26ed948e3e10/gwinferno/cosmology.py#L123

**Comment by Qazalbash** [comment]
@jaxengodfrey can you assist in [comment1](https://github.com/FarrOutLab/GWInferno/issues/24#issuecomment-2462792273) and [comment2](https://github.com/FarrOutLab/GWInferno/issues/24#issuecomment-2462975677). Consider this an urgent request. Thank you!

**Comment by jaxengodfrey** [comment]
@Qazalbash Thanks for pointing out the issue with `DL2z`. I don't know when I will have the time to fix the problem, but a possible solution would be to increase the default value of the `max_z` kwarg when `Cosmology` is initialized so that you don't need to use `extend` to recalculate DL. This may not work given that you said the `jnp.greater` lines produce the same error.  In order to help with that, I need more information about how you're using `Cosmology` so I can reproduce the error you're getting.

**Comment by Qazalbash** [comment]
We have adopted the `gwinferno.cosmology.Cosmology`[^1] and `gwinferno.numpyro_models.PowerlawRedshift`[^2] with some modifications. The modifications are slight and I assume the error is reproducible on your implementation too. Error is reproducible from following script.

```python
import jax
from jax import numpy as jnp

from gwkokab.models import PowerlawRedshift


lamb = 2.1
z_max = 5.0
zz = jnp.linspace(0.001, z_max + 1.0, 1000)  # more than z_max


@jax.jit
def prob(lamb, z_max):
    model = PowerlawRedshift(lamb=lamb, z_max=z_max, validate_args=True)
    return jnp.exp(model.log_prob(zz))


print(prob(lamb, z_max))
```

This script throws error:

```bash
Traceback (most recent call last):
  File "/media/gradf/academia/gwkokab/playground.py", line 18, in <module>
    print(prob(lamb, z_max))
          ^^^^^^^^^^^^^^^^^
  File "/media/gradf/academia/gwkokab/playground.py", line 14, in prob
    model = PowerlawRedshift(lamb=lamb, z_max=z_max, validate_args=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/numpyro/distributions/distribution.py", line 100, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/gwkokab/models/redshift/_models.py", line 81, in __init__
    self.dVdc_ = 4.0 * jnp.pi * PLANCK_2015_Cosmology.dVcdz(self.zs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/gwkokab/cosmology/_cosmology.py", line 116, in dVcdz
    return jnp.exp(self.logdVcdz(z, Dc=Dc, dz=dz))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/gwkokab/cosmology/_cosmology.py", line 122, in logdVcdz
    Dc = self.z_to_Dc(z, dz=dz)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/gwkokab/cosmology/_cosmology.py", line 128, in z_to_Dc
    if jnp.greater(max_z, jnp.max(self.z)):
jax.errors.TracerBoolConversionError: Attempted boolean conversion of traced array with shape bool[].
The error occurred while tracing the function prob at /media/gradf/academia/gwkokab/playground.py:12 for jit. This concrete value was not available in Python because it depends on the value of the argument z_max.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerBoolConversionError
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```


[^1]: [`gwkokab.cosmology.Cosmology`](https://github.com/gwkokab/gwkokab/blob/ref-powerlaw-redshift/src/gwkokab/cosmology/_cosmology.py)
[^2]: [`gwkokab.models.PowerlawRedshift`](https://github.com/gwkokab/gwkokab/blob/ref-powerlaw-redshift/src/gwkokab/models/redshift/_models.py)

**Comment by jaxengodfrey** [comment]
Adding the `jit` decorator triggers the error. Given that we haven't designed `Cosmology` or `PowerlawRedshift` to be jitted and don't intend to in the near future, I can't offer any more insight. Since `gwkokab` does inference entirely in `jax`, I would guess you're in a better position to solve this issue than I am anyways.

Also, since you directly copy these functions to your project with minimal changes, could you add a note in your versions saying that they originally came from this repository? Thanks!

**Comment by Qazalbash** [comment]
> Adding the jit decorator triggers the error. Given that we haven't designed Cosmology or PowerlawRedshift to be jitted and don't intend to in the near future, I can't offer any more insight. Since gwkokab does inference entirely in jax, I would guess you're in a better position to solve this issue than I am anyways.

Thanks for looking into it.

> Also, since you directly copy these functions to your project with minimal changes, could you add a note in your versions saying that they originally came from this repository? Thanks!

I have added GWInferno's distribution license to each file. If you want an explicit mention, I would love to add that, too.
